from typing import List, Dict, Any
from dataclasses import dataclass, field

from ...models.task import Task
from ...models.work_result import WorkResult
from ..base import BaseWorker
from .planner_agent import Plan, Step


@dataclass
class ExecutionLog:
    """Record of execution results for a plan."""
    plan_id: str
    executed_steps: Dict[str, WorkResult] = field(default_factory=dict)
    failed_step_id: str = None  # Set if execution stopped due to failure

    def all_succeeded(self) -> bool:
        """Check if all executed steps succeeded."""
        return all(result.success for result in self.executed_steps.values())


class ExecutorAgent(BaseWorker):
    """Agent that executes a plan by running each step in sequence.
    
    The executor takes a Plan (generated by PlannerAgent) and executes
    each step using a worker implementation. It respects dependencies
    and stops on failure (fail-fast strategy).
    """

    def __init__(self, worker: BaseWorker):
        """
        Args:
            worker: BaseWorker implementation that will execute individual steps.
                   The worker should handle the action types specified in Plan steps.
        """
        self.worker = worker

    def execute(self, task: Task) -> WorkResult:
        """Execute a task with the expectation that the task.input contains a Plan."""
        try:
            # The executor expects the input to be a Plan object
            # (typically passed from PlannerAgent output)
            if isinstance(task.input, dict) and "steps" in task.input:
                # Handle dict-serialized Plan (for flexibility)
                plan = self._deserialize_plan(task.input)
            elif isinstance(task.input, Plan):
                plan = task.input
            else:
                return WorkResult(
                    success=False,
                    error="ExecutorAgent expects task.input to be a Plan or Plan dict"
                )

            log = self._execute_plan(plan)
            return WorkResult(success=log.all_succeeded(), output=log)
        except Exception as e:
            return WorkResult(success=False, error=str(e))

    def _execute_plan(self, plan: Plan) -> ExecutionLog:
        """Execute all steps in the plan, respecting dependencies."""
        log = ExecutionLog(plan_id=plan.task_id)

        # Simple sequential execution (no parallelism yet)
        for step in plan.steps:
            # Check if all dependencies have been executed successfully
            if not self._check_dependencies(step, log):
                log.failed_step_id = step.id
                return log

            # Execute the step
            print(f"Executing step: {step.id} — {step.description}")
            step_task = Task(id=step.id, type=step.action, input=step.input)
            result = self.worker.execute(step_task)
            log.executed_steps[step.id] = result

            # If this step failed, stop execution
            if not result.success:
                log.failed_step_id = step.id
                return log

        return log

    def _check_dependencies(self, step: Step, log: ExecutionLog) -> bool:
        """Verify that all dependencies of a step have succeeded."""
        for dep_id in step.dependencies:
            if dep_id not in log.executed_steps:
                # Dependency was never executed
                return False
            if not log.executed_steps[dep_id].success:
                # Dependency failed
                return False
        return True

    def _deserialize_plan(self, plan_dict: Dict[str, Any]) -> Plan:
        """Convert a dict representation back to a Plan object."""
        # This is a helper for flexibility, allowing Plans to be serialized/deserialized
        steps = []
        for step_dict in plan_dict.get("steps", []):
            step = Step(
                id=step_dict["id"],
                description=step_dict["description"],
                action=step_dict["action"],
                input=step_dict.get("input", {}),
                dependencies=step_dict.get("dependencies", []),
            )
            steps.append(step)
        return Plan(task_id=plan_dict["task_id"], steps=steps)
